Update createToken to accept token "type"
CESARBR/knot-cloud-sdk-js-authenticator pull request #17
Opened 2020-05-29 14:57 UTC by esdrasjnr

This patch sync the authenticator SDK with babeltower changes

2020-06-10 12:45 UTC, netoax requested changes
Thanks for the PR!
I made some comments to help you improve it.

2020-06-10 12:45 UTC, netoax commented on src/Client.js
> +  async createUserToken(email, password) {
I think it's simpler to change the `createToken` signature to support new properties such as `type` and `duration` instead of creating another method. As they have default values, this change wouldn't break the current API.

2020-06-10 12:45 UTC, netoax commented on src/Client.js
> +  async createAppToken(email, token, duration = 0) {
In `babeltower` we already default `duration` to one year, this change would require the user to pass it every time.

2020-06-10 14:03 UTC, esdrasjnr commented on src/Client.js
> +  async createUserToken(email, password) {
Done!

2020-06-10 14:03 UTC, esdrasjnr commented on src/Client.js
> +  async createAppToken(email, token, duration = 0) {
Done!

2020-06-10 14:30 UTC, lcbm requested changes
Awesome patch, made a single remark! :smile:

2020-06-10 14:30 UTC, lcbm commented on src/Client.js
>      return this.http.post('tokens', body);
Have you tested this request? I remember being rejected when inserting invalid parameters while creating an `App` token... :thinking: 

I don't see a problem in adding an `if-else` statement checking the value of `type`. Remember that `type` and `duration` should be optional, `type` should default to `user` and `duration` to ~~[forever](https://github.com/mainflux/mainflux/pull/1104/commits)~~ 1 year :grimacing:.

2020-06-12 12:41 UTC, netoax commented on src/Client.js
>      return this.http.post('tokens', body);
@lcbm as pointed in the slack we aren't supporting tokens with infinite duration yet.

2020-06-12 13:36 UTC, lcbm commented on src/Client.js
>      return this.http.post('tokens', body);
Updated the comment!

2020-06-12 14:47 UTC, esdrasjnr commented on src/Client.js
>      return this.http.post('tokens', body);
I tested and it runs correctly here :thinking:

2020-06-12 15:16 UTC, netoax approved these changes
LGTM!

2020-06-12 17:16 UTC, lcbm approved these changes
LGTM! :smile:

2020-06-12 18:56 UTC, merged